image: python:3.11

stages:
  - testing
  - build
  - deploy

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

lint:
  stage: testing
  script:
     - pylint $(git ls-files '*.py')

test:
  stage: testing
  services:
    - postgres
  variables:
    POSTGRES_DB: meter
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: postgres
    COVERAGE_DIR: "coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  script:
    - python manage.py migrate
    - pytest -s --cov-report html:$COVERAGE_DIR --cov-fail-under 90
  artifacts:
    name: $COVERAGE_DIR
    paths:
      - $COVERAGE_DIR
    when: on_success
    expire_in: 1 week

make-build:
  stage: build
  script:
    - echo "Make build"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."