image: python:3.11

stages:
  - testing
  - build
  - deploy

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

lint:
  stage: testing
  script:
     - pylint $(git ls-files '*.py')

test:
  stage: testing
  before_script:
    - pip install PyYAML==5.3.1
    - pip install docker-compose==1.29.2
    - sleep 3
    - python manage.py migrate
    - python manage.py create_db_meters
  services:
    - postgres
  variables:
    POSTGRES_DB: meter
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: pg
  script:
    - docker-compose build
    - docker-compose up -d pg
    - pytest -s --cov --cov-report --cov-fail-under 71

make-build:
  stage: build
  script:
    - echo "Make build"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."