stages:
  - testing
  - build
  - deploy

lint:
  stage: testing
  before_script:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
  script:
     - pylint $(git ls-files '*.py')

test:
  stage: testing
  script:
    - pytest -s --cov --cov-report --cov-fail-under 71

make-build:
  stage: build
  script:
    - echo "Make build"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."