version: "3"

services:

  pg:
    image: postgres
    environment:
     - POSTGRES_DB=meter
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
    volumes:
        - db-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d meter -U user" ]
      interval: 5s
      timeout: 3s
      retries: 5
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@pg:5432/meter"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - .:/usr/src/meter_app/

volumes:
  db-data: