name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [ "3.10", "3.11" ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: meter
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
            python-version: ${{ matrix.python-version }}
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev_requirements.txt

      - name: Connect to PostgreSQL
        run: python manage.py migrate
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Test project with pytest
        run: |
          python manage.py migrate
          pytest -s --cov --cov-fail-under 90